.ONESHELL:

.DEFAULT_GOAL := run

PYTHON = venv/Scripts/python
PIP = venv/Scripts/pip

venv/Scripts/activate : requirements.txt
	python -m venv venv
	venv/Scripts/activate.bat
	${PIP} install -r requirements.txt

venv: venv/Scripts/activate
	venv\Scripts\activate.bat

run: venv 
	${PYTHON} src/main.py

clean:
	rm -rf __pycache__
	rm -rf venv

.PHONY: run clean
