name: Generate docs
on:
  push:
    branches: ["main"]
    paths:
      - mkdocs.yml
      - docs/**
      - .github/workflows/mkdocs.yml
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest         
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install mkdocs
        run: pip install mkdocs
      - name: GH deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_DOCS }}
        run: git pull && mkdocs gh-deploy
