name: Generate docs
on:
  push:
    branches: ["main"]
    paths:
      - mkdocs.yml
      - docs/**
      - .github/workflows/mkdocs.yml
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 'pypy-3.6'

      - name: Deploy docs
        uses: afritzler/mkdocs-gh-pages-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_DOCS }}
