name: Upload artifact
on:
  push:
  workflow_dispatch:
jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Create a file
      run: |
        env | sort > short_lived_file_env.txt
        echo "short lived file 1" > short_lived_file1.txt
        echo "short lived file 2" > short_lived_file2.txt
        zip files-${{ env.GITHUB_RUN_NUMBER }}.zip short_lived_file*.txt
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: short-lived-artifact-${{github.run_number}}
        path: files-${{github.run_number}}.zip
        retention-days: 1
